"""search profiles and app settings

Revision ID: 3374777f0db4
Revises: f35d01e216d8
Create Date: 2026-07-21 02:40:45.736182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3374777f0db4'
down_revision: Union[str, Sequence[str], None] = 'f35d01e216d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('search_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('term', sa.String(length=256), nullable=False),
    sa.Column('location', sa.String(length=256), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('sites', postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), 'sqlite'), nullable=False),
    sa.Column('experience', sa.String(length=64), nullable=True),
    sa.Column('schedule_hour', sa.Integer(), nullable=False),
    sa.Column('schedule_minute', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_search_profiles_enabled'), 'search_profiles', ['enabled'], unique=False)
    op.add_column('runs', sa.Column('profile_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_runs_profile_id'), 'runs', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'runs', 'search_profiles', ['profile_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Seed search_profiles from the current SEARCHES environment value so
    # behaviour is unchanged after profiles supersede SEARCHES (ADR-0005).
    _seed_profiles_from_env()


def _seed_profiles_from_env() -> None:
    """Insert one search_profiles row per configured SearchSpec."""
    from app.config import settings

    profiles = sa.table(
        "search_profiles",
        sa.column("name", sa.String),
        sa.column("term", sa.String),
        sa.column("location", sa.String),
        sa.column("country", sa.String),
        sa.column("is_remote", sa.Boolean),
        sa.column("sites", postgresql.JSONB().with_variant(sa.JSON(), "sqlite")),
        sa.column("schedule_hour", sa.Integer),
        sa.column("schedule_minute", sa.Integer),
        sa.column("enabled", sa.Boolean),
    )

    rows = []
    seen: set[str] = set()
    for spec in settings.searches:
        base = spec.term + (" (remote)" if spec.is_remote else f" @ {spec.location or 'any'}")
        name = base
        n = 2
        while name in seen:
            name = f"{base} #{n}"
            n += 1
        seen.add(name)
        rows.append({
            "name": name[:128],
            "term": spec.term,
            "location": spec.location,
            "country": spec.country,
            "is_remote": spec.is_remote,
            "sites": list(spec.sites),
            "schedule_hour": settings.schedule_hour,
            "schedule_minute": settings.schedule_minute,
            "enabled": True,
        })

    if rows:
        op.bulk_insert(profiles, rows)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_index(op.f('ix_runs_profile_id'), table_name='runs')
    op.drop_column('runs', 'profile_id')
    op.drop_index(op.f('ix_search_profiles_enabled'), table_name='search_profiles')
    op.drop_table('search_profiles')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
