"""initial schema

Revision ID: ff6adc50ab28
Revises: 
Create Date: 2026-07-20 21:41:13.291012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff6adc50ab28'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Created up front though no column uses it yet: phase 2 vector matching
    # (design §14) is the stated reason PostgreSQL was chosen over SQLite (D4).
    # Enabling it here avoids a migration whose only purpose is an extension.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('normalised_name', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=True),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('num_employees', sa.String(length=64), nullable=True),
    sa.Column('revenue', sa.String(length=64), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employers_normalised_name'), 'employers', ['normalised_name'], unique=True)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('collected_count', sa.Integer(), nullable=False),
    sa.Column('deduplicated_count', sa.Integer(), nullable=False),
    sa.Column('filter_passed_count', sa.Integer(), nullable=False),
    sa.Column('filter_rejected_count', sa.Integer(), nullable=False),
    sa.Column('scored_count', sa.Integer(), nullable=False),
    sa.Column('published_count', sa.Integer(), nullable=False),
    sa.Column('counts_by_site', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_started_at'), 'runs', ['started_at'], unique=False)
    op.create_table('postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('employer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('normalised_title', sa.String(length=512), nullable=False),
    sa.Column('location_raw', sa.String(length=256), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('is_remote', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date_posted', sa.Date(), nullable=True),
    sa.Column('job_type', sa.String(length=64), nullable=True),
    sa.Column('sources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('title_filter_passed', sa.Boolean(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('matched_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('gaps', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('scored_by_model', sa.String(length=128), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('notion_page_id', sa.String(length=64), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('suppressed', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['employer_id'], ['employers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_postings_country_code'), 'postings', ['country_code'], unique=False)
    op.create_index(op.f('ix_postings_date_posted'), 'postings', ['date_posted'], unique=False)
    op.create_index(op.f('ix_postings_employer_id'), 'postings', ['employer_id'], unique=False)
    op.create_index(op.f('ix_postings_fingerprint'), 'postings', ['fingerprint'], unique=True)
    op.create_index('ix_postings_publish_queue', 'postings', ['published', 'score', 'suppressed'], unique=False)
    op.create_index(op.f('ix_postings_published'), 'postings', ['published'], unique=False)
    op.create_index(op.f('ix_postings_score'), 'postings', ['score'], unique=False)
    op.create_table('raw_postings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('site', sa.String(length=64), nullable=False),
    sa.Column('site_job_id', sa.String(length=256), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('collected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_postings_run_id'), 'raw_postings', ['run_id'], unique=False)
    op.create_index(op.f('ix_raw_postings_site'), 'raw_postings', ['site'], unique=False)
    op.create_index(op.f('ix_raw_postings_site_job_id'), 'raw_postings', ['site_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_raw_postings_site_job_id'), table_name='raw_postings')
    op.drop_index(op.f('ix_raw_postings_site'), table_name='raw_postings')
    op.drop_index(op.f('ix_raw_postings_run_id'), table_name='raw_postings')
    op.drop_table('raw_postings')
    op.drop_index(op.f('ix_postings_score'), table_name='postings')
    op.drop_index(op.f('ix_postings_published'), table_name='postings')
    op.drop_index('ix_postings_publish_queue', table_name='postings')
    op.drop_index(op.f('ix_postings_fingerprint'), table_name='postings')
    op.drop_index(op.f('ix_postings_employer_id'), table_name='postings')
    op.drop_index(op.f('ix_postings_date_posted'), table_name='postings')
    op.drop_index(op.f('ix_postings_country_code'), table_name='postings')
    op.drop_table('postings')
    op.drop_index(op.f('ix_runs_started_at'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_employers_normalised_name'), table_name='employers')
    op.drop_table('employers')
    # ### end Alembic commands ###

    # The vector extension is deliberately NOT dropped. Dropping an extension
    # is database-wide rather than schema-local, so a downgrade of this
    # migration should not remove a capability anything else may depend on.
